server:
  port: 8080 # Puerto único y central 

spring:
  application:
    name: gateway-service

  cloud:
    compatibility-verifier:
      enabled: false
      
    gateway:
      routes:
        # 1. MICROSERVICIO DE GÉNEROS
        - id: generos-service
          uri: ${URI_GENEROS:http://localhost:8081}
          predicates:
            - Path=/api/v1/generos/**

        # 2. MICROSERVICIO DE PLATAFORMAS
        - id: plataformas-service
          uri: ${URI_PLATAFORMAS:http://localhost:8082}
          predicates:
            - Path=/api/v1/plataformas/**

        # 3. MICROSERVICIO DE VIDEOJUEGOS
        - id: videojuegos-service
          uri: ${URI_JUEGOS:http://localhost:8083}
          predicates:
            - Path=/api/v1/juegos/**

        # 4. MICROSERVICIO DE ESTUDIOS
        - id: estudios-service
          uri: ${URI_ESTUDIOS:http://localhost:8084}
          predicates:
            - Path=/api/v1/estudios/**

        # 5. MICROSERVICIO DE USUARIOS
        - id: usuarios-service
          uri: ${URI_USUARIOS:http://localhost:8085}
          predicates:
            - Path=/api/v1/usuarios/**

        # 6. MICROSERVICIO DE RESEÑAS
        - id: resenas-service
          uri: ${URI_RESENAS:http://localhost:8086}
          predicates:
            - Path=/api/v1/resenas/**